version: '3'

services:
  client:
    build: ./client
    ports:
      - "4200:80"
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true

  server:
    build: ./server
    ports:
      - "8000:9000"
    volumes:
      - ./server:/var/www/html
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
